"""
Every place his two copies of a trait dictionary disagree, side by side.

He keeps two copies of each trait dictionary -- one the character sheet reads for racial
abilities, one the creature sheet reads -- and they have drifted apart. The content build
keeps the creature row wherever they differ (docs/UPSTREAM-ISSUES.md item 10) and reports the
count; this writes out WHICH rows, in a form he can read and rule on.

    python tools/extract/report_trait_conflicts.py

Writes docs/reference/trait-conflicts.md. Regenerate it rather than editing it.
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
NAMED = os.path.join(ROOT, "src", "packs", "named")
OUT = os.path.join(ROOT, "docs", "reference", "trait-conflicts.md")

# Which pair of dictionaries feeds each category, creature copy first. Same pairing the content
# build uses; kept here rather than imported so this script stands alone.
SOURCES = {
    "ability":    ("abilitylist@176213",    "abilitylist@45725"),
    "disability": ("disabilitylist@177698", "disabilitylist@45903"),
    "immunity":   ("immunitylist@177965",   "immunitylist@45988"),
}

FIELDS = ["canonicalName", "value1", "value2", "description"]


def load(tmpname):
    tmppath = os.path.join(NAMED, tmpname + ".json")
    if not os.path.exists(tmppath):
        return {}
    with io.open(tmppath, encoding="utf-8") as fh:
        return json.load(fh).get("entries", {})


def cell(tmptext):
    """One field, made safe to sit in a markdown table cell."""
    tmpout = str(tmptext if tmptext is not None else "").replace("|", "\\|")
    tmpout = " ".join(tmpout.split())
    return tmpout if tmpout else "*(blank)*"


def main():
    tmplines = [
        "# Where the two trait dictionaries disagree",
        "",
        "Generated by `tools/extract/report_trait_conflicts.py` -- regenerate rather than edit.",
        "",
        "You keep two copies of each trait dictionary: one the character sheet reads for racial",
        "abilities, one the creature sheet reads. They have drifted apart. This lists every row",
        "where the two differ, and every row only one of them has.",
        "",
        "**What the conversion does today:** where both have a row and they differ, it keeps the",
        "**creature** row, on your word that \"the creature listings are right\". Where only the",
        "racial list has a row, it keeps that. Nothing here has been changed in your data -- this",
        "is a list for you to rule on, and anything you want flipped is a one-line change.",
        "",
        "The column that matters most is **canonical name**: your racial code switches on it, so a",
        "name that differs between the two copies will not match its `case` when it comes from the",
        "wrong list.",
        "",
    ]

    for tmpcategory in ["ability", "disability", "immunity"]:
        tmpcreaturename, tmpracialname = SOURCES[tmpcategory]
        tmpcreature = load(tmpcreaturename)
        tmpracial = load(tmpracialname)

        tmpdiffer = []
        tmpracialonly = []
        tmpcreatureonly = []
        for tmpkey in sorted(set(tmpcreature) | set(tmpracial)):
            if tmpkey in tmpcreature and tmpkey in tmpracial:
                if tmpcreature[tmpkey] != tmpracial[tmpkey]:
                    tmpdiffer.append(tmpkey)
            elif tmpkey in tmpracial:
                tmpracialonly.append(tmpkey)
            else:
                tmpcreatureonly.append(tmpkey)

        tmplines += [
            "",
            "---",
            "",
            "## %s" % tmpcategory.capitalize() + ("" if tmpcategory.endswith("y") else "s"),
            "",
            "Creature copy `%s`, %d rows. Racial copy `%s`, %d rows."
            % (tmpcreaturename, len(tmpcreature), tmpracialname, len(tmpracial)),
            "",
            "**%d rows differ. %d are in the racial list only. %d are in the creature list only.**"
            % (len(tmpdiffer), len(tmpracialonly), len(tmpcreatureonly)),
            "",
        ]

        if tmpdiffer:
            # The canonical-name differences are the mechanically dangerous ones, so they lead.
            tmpnamediffer = [k for k in tmpdiffer
                             if tmpcreature[k].get("canonicalName") != tmpracial[k].get("canonicalName")]
            if tmpnamediffer:
                tmplines += [
                    "### Canonical name differs -- these are the ones that can break a `case`",
                    "",
                    "| Entry | Creature copy | Racial copy |",
                    "|---|---|---|",
                ]
                for tmpkey in tmpnamediffer:
                    tmplines.append("| `%s` | %s | %s |" % (
                        cell(tmpkey),
                        cell(tmpcreature[tmpkey].get("canonicalName")),
                        cell(tmpracial[tmpkey].get("canonicalName"))))
                tmplines.append("")

            tmpvaluediffer = [k for k in tmpdiffer
                              if (tmpcreature[k].get("value1"), tmpcreature[k].get("value2"))
                              != (tmpracial[k].get("value1"), tmpracial[k].get("value2"))]
            if tmpvaluediffer:
                tmplines += [
                    "### Values differ",
                    "",
                    "| Entry | Creature value1 | Creature value2 | Racial value1 | Racial value2 |",
                    "|---|---|---|---|---|",
                ]
                for tmpkey in tmpvaluediffer:
                    tmplines.append("| `%s` | %s | %s | %s | %s |" % (
                        cell(tmpkey),
                        cell(tmpcreature[tmpkey].get("value1")), cell(tmpcreature[tmpkey].get("value2")),
                        cell(tmpracial[tmpkey].get("value1")), cell(tmpracial[tmpkey].get("value2"))))
                tmplines.append("")

            tmpdesconly = [k for k in tmpdiffer if k not in tmpnamediffer and k not in tmpvaluediffer]
            if tmpdesconly:
                tmplines += [
                    "### Description differs only",
                    "",
                    "Text, not mechanics -- but worth a glance in case one of them is the newer wording.",
                    "",
                ]
                for tmpkey in tmpdesconly:
                    tmplines += [
                        "**%s**" % tmpkey,
                        "",
                        "- creature: %s" % cell(tmpcreature[tmpkey].get("description")),
                        "- racial: %s" % cell(tmpracial[tmpkey].get("description")),
                        "",
                    ]

        if tmpracialonly:
            tmplines += [
                "### In the racial list only",
                "",
                "Your creature lookup can never reach these, but a character's race still grants them.",
                "",
                "| Entry | Canonical name | value1 | value2 |",
                "|---|---|---|---|",
            ]
            for tmpkey in tmpracialonly:
                tmprow = tmpracial[tmpkey]
                tmplines.append("| `%s` | %s | %s | %s |" % (
                    cell(tmpkey), cell(tmprow.get("canonicalName")),
                    cell(tmprow.get("value1")), cell(tmprow.get("value2"))))
            tmplines.append("")

        if tmpcreatureonly:
            tmplines += [
                "### In the creature list only",
                "",
                "%d rows. These are the bulk of the creature list and are listed by name only."
                % len(tmpcreatureonly),
                "",
                ", ".join("`%s`" % k for k in tmpcreatureonly),
                "",
            ]

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(tmplines) + "\n")

    print("wrote %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
