"""
Every place his two copies of a trait dictionary disagree, side by side.

He keeps two copies of each trait dictionary -- one the character sheet reads for racial
abilities, one the creature sheet reads -- and they have drifted apart. The content build
keeps the creature row wherever they differ (docs/UPSTREAM-ISSUES.md item 10) and reports the
count; this writes out WHICH rows, in a form he can read and rule on.

    python tools/extract/report_trait_conflicts.py

Writes docs/reference/trait-conflicts.md. Regenerate it rather than editing it.
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
NAMED = os.path.join(ROOT, "src", "packs", "named")
OUT = os.path.join(ROOT, "docs", "reference", "trait-conflicts.md")

# Which pair of dictionaries feeds each category, creature copy first. Same pairing the content
# build uses; kept here rather than imported so this script stands alone.
SOURCES = {
    "ability":    ("abilitylist@176213",    "abilitylist@45725"),
    "disability": ("disabilitylist@177698", "disabilitylist@45903"),
    "immunity":   ("immunitylist@177965",   "immunitylist@45988"),
}

FIELDS = ["canonicalName", "value1", "value2", "description"]


def load(tmpname):
    tmppath = os.path.join(NAMED, tmpname + ".json")
    if not os.path.exists(tmppath):
        return {}
    with io.open(tmppath, encoding="utf-8") as fh:
        return json.load(fh).get("entries", {})


def cell(tmptext):
    """One field, made safe to sit in a markdown table cell."""
    tmpout = str(tmptext if tmptext is not None else "").replace("|", "\\|")
    tmpout = " ".join(tmpout.split())
    return tmpout if tmpout else "*(blank)*"


def main():
    tmplines = [
        "# Where the two trait dictionaries disagree",
        "",
        "Generated by `tools/extract/report_trait_conflicts.py` -- regenerate rather than edit.",
        "",
        "You keep two copies of each trait dictionary: one the character sheet reads for racial",
        "abilities, one the creature sheet reads. They have drifted apart.",
        "",
        "**Most of what follows needs nothing from you.** The creature list is simply bigger and",
        "more actively maintained than the racial one -- hundreds of creature-only entries below",
        "are expected, not a question. The conversion already keeps the creature row wherever the",
        "two disagree, on your word that \"the creature listings are right\", and keeps a racial-only",
        "row where the creature list has nothing. **The only real decisions are the two short lists",
        "right here.**",
        "",
    ]

    # The narrow, actionable ask, computed from the same data the full detail below comes from
    # so the two can never drift apart. Everything else in this file is FYI.
    for tmpcategory in ["ability", "disability", "immunity"]:
        tmpcreaturename, tmpracialname = SOURCES[tmpcategory]
        tmpcreature = load(tmpcreaturename)
        tmpracial = load(tmpracialname)
        tmpnamediffer = [k for k in (set(tmpcreature) & set(tmpracial))
                         if tmpcreature[k].get("canonicalName") != tmpracial[k].get("canonicalName")]
        tmpvaluediffer = [k for k in (set(tmpcreature) & set(tmpracial))
                          if (tmpcreature[k].get("value1"), tmpcreature[k].get("value2"))
                          != (tmpracial[k].get("value1"), tmpracial[k].get("value2"))
                          and k not in tmpnamediffer]
        if not tmpnamediffer and not tmpvaluediffer:
            continue

        if tmpnamediffer:
            tmplines += [
                "## Needs your call: which name is right (%s)" % tmpcategory,
                "",
                "Your racial code switches on canonical name, so picking the wrong one silently",
                "breaks that ability for a character built from the racial list. Say which spelling",
                "is the one you actually mean, per row, or say \"creature always wins\" and this",
                "whole list resolves at once.",
                "",
                "| Entry | Creature says | Racial says |",
                "|---|---|---|",
            ]
            for tmpkey in sorted(tmpnamediffer):
                tmplines.append("| `%s` | %s | %s |" % (
                    cell(tmpkey), cell(tmpcreature[tmpkey].get("canonicalName")),
                    cell(tmpracial[tmpkey].get("canonicalName"))))
            tmplines.append("")

        if tmpvaluediffer:
            tmplines += [
                "## Needs your call: which value is right (%s)" % tmpcategory,
                "",
                "| Entry | Creature value1 | Creature value2 | Racial value1 | Racial value2 |",
                "|---|---|---|---|---|",
            ]
            for tmpkey in sorted(tmpvaluediffer):
                tmplines.append("| `%s` | %s | %s | %s | %s |" % (
                    cell(tmpkey),
                    cell(tmpcreature[tmpkey].get("value1")), cell(tmpcreature[tmpkey].get("value2")),
                    cell(tmpracial[tmpkey].get("value1")), cell(tmpracial[tmpkey].get("value2"))))
            tmplines.append("")

    tmplines += [
        "---",
        "",
        "**One thing worth knowing, not deciding:** `Vibration Language` and `Vibration Sensing`",
        "have their descriptions swapped in your RACIAL list -- the racial copy of \"Vibration",
        "Language\" actually describes sensing, and the racial copy of \"Vibration Sensing\"",
        "describes speaking. The creature copy of both is correct, and the conversion already uses",
        "the creature copy, so nothing needs fixing on this end -- flagged only because it looks",
        "like a genuine copy-paste swap in your own data, in case it is worth fixing at the source.",
        "",
        "Everything below this point is the full detail behind the counts above, kept for",
        "reference. None of it needs a reply.",
        "",
    ]

    for tmpcategory in ["ability", "disability", "immunity"]:
        tmpcreaturename, tmpracialname = SOURCES[tmpcategory]
        tmpcreature = load(tmpcreaturename)
        tmpracial = load(tmpracialname)

        tmpdiffer = []
        tmpracialonly = []
        tmpcreatureonly = []
        for tmpkey in sorted(set(tmpcreature) | set(tmpracial)):
            if tmpkey in tmpcreature and tmpkey in tmpracial:
                if tmpcreature[tmpkey] != tmpracial[tmpkey]:
                    tmpdiffer.append(tmpkey)
            elif tmpkey in tmpracial:
                tmpracialonly.append(tmpkey)
            else:
                tmpcreatureonly.append(tmpkey)

        tmplines += [
            "",
            "---",
            "",
            "## %s" % tmpcategory.capitalize() + ("" if tmpcategory.endswith("y") else "s"),
            "",
            "Creature copy `%s`, %d rows. Racial copy `%s`, %d rows."
            % (tmpcreaturename, len(tmpcreature), tmpracialname, len(tmpracial)),
            "",
            "**%d rows differ. %d are in the racial list only. %d are in the creature list only.**"
            % (len(tmpdiffer), len(tmpracialonly), len(tmpcreatureonly)),
            "",
        ]

        if tmpdiffer:
            # The two decisions above (canonical name, values) are already surfaced at the top of
            # the file. Only description-only differences are new information here, and even those
            # are not a decision -- text with no mechanical weight.
            tmpnamediffer = [k for k in tmpdiffer
                             if tmpcreature[k].get("canonicalName") != tmpracial[k].get("canonicalName")]
            tmpvaluediffer = [k for k in tmpdiffer
                              if (tmpcreature[k].get("value1"), tmpcreature[k].get("value2"))
                              != (tmpracial[k].get("value1"), tmpracial[k].get("value2"))
                              and k not in tmpnamediffer]
            # Called out by name above rather than buried here, since their swap is the interesting
            # part and a plain creature/racial listing would hide that.
            tmpalreadyflagged = {"Vibration Language", "Vibration Sensing"}
            tmpdesconly = [k for k in tmpdiffer
                           if k not in tmpnamediffer and k not in tmpvaluediffer
                           and k not in tmpalreadyflagged]
            if tmpdesconly:
                tmplines += [
                    "### Description differs only -- text, no mechanical weight",
                    "",
                ]
                for tmpkey in tmpdesconly:
                    tmplines += [
                        "**%s**" % tmpkey,
                        "",
                        "- creature: %s" % cell(tmpcreature[tmpkey].get("description")),
                        "- racial: %s" % cell(tmpracial[tmpkey].get("description")),
                        "",
                    ]

        if tmpracialonly:
            tmplines += [
                "### In the racial list only",
                "",
                "Your creature lookup can never reach these, but a character's race still grants them.",
                "",
                "| Entry | Canonical name | value1 | value2 |",
                "|---|---|---|---|",
            ]
            for tmpkey in tmpracialonly:
                tmprow = tmpracial[tmpkey]
                tmplines.append("| `%s` | %s | %s | %s |" % (
                    cell(tmpkey), cell(tmprow.get("canonicalName")),
                    cell(tmprow.get("value1")), cell(tmprow.get("value2"))))
            tmplines.append("")

        if tmpcreatureonly:
            tmplines += [
                "### In the creature list only",
                "",
                "%d rows. These are the bulk of the creature list and are listed by name only."
                % len(tmpcreatureonly),
                "",
                ", ".join("`%s`" % k for k in tmpcreatureonly),
                "",
            ]

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(tmplines) + "\n")

    print("wrote %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
