// @START (CODE)
// @MARKER ATTRIBUTE LOOKUP TABLES
//==================================================================================================================
// GENERATED FILE -- do not edit by hand.
// Produced by tools/extract/generate_config_tables.py from src/packs/named/, which is in turn
// extracted from the attribute tables in the original Roll20 sheet-worker (changeAttribs).
// Regenerate rather than editing, or this will drift from his sheet.
//
// Each table is keyed by attribute rating 0-30 and holds that rating's derived modifiers.
// These are irregular lookup values, not formulas -- there is no expression that reproduces
// them, which is why they are carried as data.
//==================================================================================================================

export const ATTRIBUTE_TABLES = {

	// STR -- columns: meleeAttack, meleeDamage, loadLimit, weaponSpeed
	str: {
		0: { meleeAttack: -8, meleeDamage: -12, loadLimit: 0.005, weaponSpeed: 6 },
		1: { meleeAttack: -6, meleeDamage: -10, loadLimit: 0.01, weaponSpeed: 5 },
		2: { meleeAttack: -5, meleeDamage: -9, loadLimit: 0.02, weaponSpeed: 4 },
		3: { meleeAttack: -4, meleeDamage: -8, loadLimit: 0.03, weaponSpeed: 4 },
		4: { meleeAttack: -3, meleeDamage: -7, loadLimit: 0.04, weaponSpeed: 3 },
		5: { meleeAttack: -3, meleeDamage: -6, loadLimit: 0.05, weaponSpeed: 3 },
		6: { meleeAttack: -2, meleeDamage: -5, loadLimit: 0.1, weaponSpeed: 2 },
		7: { meleeAttack: -2, meleeDamage: -4, loadLimit: 0.2, weaponSpeed: 1 },
		8: { meleeAttack: -1, meleeDamage: -3, loadLimit: 0.4, weaponSpeed: 1 },
		9: { meleeAttack: -1, meleeDamage: -2, loadLimit: 0.6, weaponSpeed: 0 },
		10: { meleeAttack: 0, meleeDamage: -1, loadLimit: 0.8, weaponSpeed: 0 },
		11: { meleeAttack: 0, meleeDamage: 0, loadLimit: 1.0, weaponSpeed: 0 },
		12: { meleeAttack: 0, meleeDamage: 0, loadLimit: 1.1, weaponSpeed: 0 },
		13: { meleeAttack: 0, meleeDamage: 0, loadLimit: 1.2, weaponSpeed: 0 },
		14: { meleeAttack: 0, meleeDamage: 0, loadLimit: 1.3, weaponSpeed: 0 },
		15: { meleeAttack: 0, meleeDamage: 1, loadLimit: 1.4, weaponSpeed: 0 },
		16: { meleeAttack: 1, meleeDamage: 2, loadLimit: 1.5, weaponSpeed: 0 },
		17: { meleeAttack: 1, meleeDamage: 3, loadLimit: 1.6, weaponSpeed: -1 },
		18: { meleeAttack: 2, meleeDamage: 4, loadLimit: 1.7, weaponSpeed: -1 },
		19: { meleeAttack: 2, meleeDamage: 5, loadLimit: 1.8, weaponSpeed: -2 },
		20: { meleeAttack: 3, meleeDamage: 6, loadLimit: 2.0, weaponSpeed: -2 },
		21: { meleeAttack: 3, meleeDamage: 7, loadLimit: 2.2, weaponSpeed: -3 },
		22: { meleeAttack: 4, meleeDamage: 8, loadLimit: 2.4, weaponSpeed: -4 },
		23: { meleeAttack: 4, meleeDamage: 9, loadLimit: 2.6, weaponSpeed: -4 },
		24: { meleeAttack: 5, meleeDamage: 10, loadLimit: 2.8, weaponSpeed: -5 },
		25: { meleeAttack: 5, meleeDamage: 12, loadLimit: 3.0, weaponSpeed: -5 },
		26: { meleeAttack: 6, meleeDamage: 14, loadLimit: 4.0, weaponSpeed: -6 },
		27: { meleeAttack: 6, meleeDamage: 16, loadLimit: 6.0, weaponSpeed: -7 },
		28: { meleeAttack: 7, meleeDamage: 18, loadLimit: 8.0, weaponSpeed: -8 },
		29: { meleeAttack: 8, meleeDamage: 20, loadLimit: 10.0, weaponSpeed: -9 },
		30: { meleeAttack: 10, meleeDamage: 25, loadLimit: 20.0, weaponSpeed: -10 },
	},

	// AGL -- columns: missileAttack, defensiveAdjust, initiativeAdjust, weaponSpeed
	agl: {
		0: { missileAttack: -8, defensiveAdjust: 10, initiativeAdjust: 6, weaponSpeed: 6 },
		1: { missileAttack: -6, defensiveAdjust: 9, initiativeAdjust: 5, weaponSpeed: 5 },
		2: { missileAttack: -5, defensiveAdjust: 8, initiativeAdjust: 4, weaponSpeed: 4 },
		3: { missileAttack: -4, defensiveAdjust: 7, initiativeAdjust: 3, weaponSpeed: 4 },
		4: { missileAttack: -3, defensiveAdjust: 6, initiativeAdjust: 2, weaponSpeed: 3 },
		5: { missileAttack: -3, defensiveAdjust: 5, initiativeAdjust: 1, weaponSpeed: 3 },
		6: { missileAttack: -2, defensiveAdjust: 4, initiativeAdjust: 0, weaponSpeed: 2 },
		7: { missileAttack: -2, defensiveAdjust: 3, initiativeAdjust: 0, weaponSpeed: 1 },
		8: { missileAttack: -1, defensiveAdjust: 2, initiativeAdjust: 0, weaponSpeed: 1 },
		9: { missileAttack: -1, defensiveAdjust: 1, initiativeAdjust: 0, weaponSpeed: 0 },
		10: { missileAttack: 0, defensiveAdjust: 1, initiativeAdjust: -1, weaponSpeed: 0 },
		11: { missileAttack: 0, defensiveAdjust: 0, initiativeAdjust: -1, weaponSpeed: 0 },
		12: { missileAttack: 0, defensiveAdjust: 0, initiativeAdjust: -2, weaponSpeed: 0 },
		13: { missileAttack: 0, defensiveAdjust: 0, initiativeAdjust: -2, weaponSpeed: 0 },
		14: { missileAttack: 0, defensiveAdjust: 0, initiativeAdjust: -3, weaponSpeed: 0 },
		15: { missileAttack: 0, defensiveAdjust: -1, initiativeAdjust: -4, weaponSpeed: 0 },
		16: { missileAttack: 1, defensiveAdjust: -1, initiativeAdjust: -5, weaponSpeed: -1 },
		17: { missileAttack: 1, defensiveAdjust: -2, initiativeAdjust: -6, weaponSpeed: -1 },
		18: { missileAttack: 2, defensiveAdjust: -3, initiativeAdjust: -7, weaponSpeed: -2 },
		19: { missileAttack: 2, defensiveAdjust: -4, initiativeAdjust: -8, weaponSpeed: -2 },
		20: { missileAttack: 3, defensiveAdjust: -5, initiativeAdjust: -9, weaponSpeed: -3 },
		21: { missileAttack: 3, defensiveAdjust: -6, initiativeAdjust: -10, weaponSpeed: -3 },
		22: { missileAttack: 4, defensiveAdjust: -7, initiativeAdjust: -11, weaponSpeed: -4 },
		23: { missileAttack: 4, defensiveAdjust: -8, initiativeAdjust: -12, weaponSpeed: -4 },
		24: { missileAttack: 5, defensiveAdjust: -9, initiativeAdjust: -13, weaponSpeed: -5 },
		25: { missileAttack: 5, defensiveAdjust: -10, initiativeAdjust: -14, weaponSpeed: -5 },
		26: { missileAttack: 6, defensiveAdjust: -11, initiativeAdjust: -15, weaponSpeed: -6 },
		27: { missileAttack: 6, defensiveAdjust: -12, initiativeAdjust: -16, weaponSpeed: -7 },
		28: { missileAttack: 7, defensiveAdjust: -13, initiativeAdjust: -17, weaponSpeed: -8 },
		29: { missileAttack: 8, defensiveAdjust: -14, initiativeAdjust: -18, weaponSpeed: -9 },
		30: { missileAttack: 10, defensiveAdjust: -15, initiativeAdjust: -21, weaponSpeed: -10 },
	},

	// VIT -- columns: healingRate, poisonResist, diseaseResist
	vit: {
		0: { healingRate: "1 per 2 months", poisonResist: 0, diseaseResist: 0 },
		1: { healingRate: "1 per month", poisonResist: 0, diseaseResist: 0 },
		2: { healingRate: "1 per month", poisonResist: 0, diseaseResist: 0 },
		3: { healingRate: "1 per 2 weeks", poisonResist: 0, diseaseResist: 0 },
		4: { healingRate: "1 per 2 weeks", poisonResist: 1, diseaseResist: 0 },
		5: { healingRate: "1 per week", poisonResist: 2, diseaseResist: 1 },
		6: { healingRate: "1 per week", poisonResist: 5, diseaseResist: 2 },
		7: { healingRate: "1 per 6 days", poisonResist: 10, diseaseResist: 5 },
		8: { healingRate: "1 per 6 days", poisonResist: 15, diseaseResist: 10 },
		9: { healingRate: "1 per 5 days", poisonResist: 20, diseaseResist: 15 },
		10: { healingRate: "1 per 4 days", poisonResist: 25, diseaseResist: 20 },
		11: { healingRate: "1 per 3 days", poisonResist: 30, diseaseResist: 25 },
		12: { healingRate: "1 per 3 days", poisonResist: 35, diseaseResist: 30 },
		13: { healingRate: "1 per 2 days", poisonResist: 40, diseaseResist: 35 },
		14: { healingRate: "1 per 2 days", poisonResist: 45, diseaseResist: 40 },
		15: { healingRate: "1 per day", poisonResist: 50, diseaseResist: 45 },
		16: { healingRate: "1 per day", poisonResist: 55, diseaseResist: 50 },
		17: { healingRate: "2 per day", poisonResist: 60, diseaseResist: 55 },
		18: { healingRate: "2 per day", poisonResist: 65, diseaseResist: 60 },
		19: { healingRate: "3 per day", poisonResist: 70, diseaseResist: 65 },
		20: { healingRate: "3 per day", poisonResist: 75, diseaseResist: 70 },
		21: { healingRate: "4 per day", poisonResist: 80, diseaseResist: 75 },
		22: { healingRate: "4 per day", poisonResist: 85, diseaseResist: 80 },
		23: { healingRate: "5 per day", poisonResist: 90, diseaseResist: 85 },
		24: { healingRate: "5 per day", poisonResist: 92, diseaseResist: 90 },
		25: { healingRate: "1 per hour", poisonResist: 94, diseaseResist: 92 },
		26: { healingRate: "1 per 30 minutes", poisonResist: 96, diseaseResist: 94 },
		27: { healingRate: "1 per 10 minutes", poisonResist: 98, diseaseResist: 96 },
		28: { healingRate: "1 per minute", poisonResist: 99, diseaseResist: 98 },
		29: { healingRate: "1 per 10 seconds", poisonResist: 100, diseaseResist: 99 },
		30: { healingRate: "1 per 5 seconds", poisonResist: 200, diseaseResist: 200 },
	},

	// INT -- columns: spokenLanguages, writtenLanguages, auraControlAdjust, initiativeAdjust, controlResistAdjust
	int: {
		0: { spokenLanguages: 0, writtenLanguages: 0, auraControlAdjust: -5, initiativeAdjust: 6, controlResistAdjust: -50 },
		1: { spokenLanguages: 0, writtenLanguages: 0, auraControlAdjust: -4, initiativeAdjust: 5, controlResistAdjust: -45 },
		2: { spokenLanguages: 0, writtenLanguages: 0, auraControlAdjust: -4, initiativeAdjust: 4, controlResistAdjust: -40 },
		3: { spokenLanguages: 0, writtenLanguages: 0, auraControlAdjust: -3, initiativeAdjust: 3, controlResistAdjust: -35 },
		4: { spokenLanguages: 0.25, writtenLanguages: 0, auraControlAdjust: -3, initiativeAdjust: 2, controlResistAdjust: -25 },
		5: { spokenLanguages: 0.33, writtenLanguages: 0, auraControlAdjust: -2, initiativeAdjust: 1, controlResistAdjust: -20 },
		6: { spokenLanguages: 0.33, writtenLanguages: 0, auraControlAdjust: -2, initiativeAdjust: 0, controlResistAdjust: -15 },
		7: { spokenLanguages: 0.66, writtenLanguages: 0, auraControlAdjust: -1, initiativeAdjust: 0, controlResistAdjust: -10 },
		8: { spokenLanguages: 1, writtenLanguages: 0, auraControlAdjust: -1, initiativeAdjust: 0, controlResistAdjust: -5 },
		9: { spokenLanguages: 1, writtenLanguages: 0.33, auraControlAdjust: 0, initiativeAdjust: 0, controlResistAdjust: -5 },
		10: { spokenLanguages: 1, writtenLanguages: 0.33, auraControlAdjust: 0, initiativeAdjust: -1, controlResistAdjust: 0 },
		11: { spokenLanguages: 1, writtenLanguages: 0.66, auraControlAdjust: 0, initiativeAdjust: -1, controlResistAdjust: 0 },
		12: { spokenLanguages: 1, writtenLanguages: 0.66, auraControlAdjust: 0, initiativeAdjust: -2, controlResistAdjust: 0 },
		13: { spokenLanguages: 1, writtenLanguages: 1, auraControlAdjust: 0, initiativeAdjust: -2, controlResistAdjust: 0 },
		14: { spokenLanguages: 2, writtenLanguages: 1, auraControlAdjust: 0, initiativeAdjust: -3, controlResistAdjust: 0 },
		15: { spokenLanguages: 2, writtenLanguages: 1, auraControlAdjust: 0, initiativeAdjust: -4, controlResistAdjust: 0 },
		16: { spokenLanguages: 3, writtenLanguages: 1, auraControlAdjust: 0, initiativeAdjust: -5, controlResistAdjust: 5 },
		17: { spokenLanguages: 3, writtenLanguages: 2, auraControlAdjust: 1, initiativeAdjust: -6, controlResistAdjust: 5 },
		18: { spokenLanguages: 4, writtenLanguages: 2, auraControlAdjust: 1, initiativeAdjust: -7, controlResistAdjust: 10 },
		19: { spokenLanguages: 5, writtenLanguages: 3, auraControlAdjust: 2, initiativeAdjust: -8, controlResistAdjust: 15 },
		20: { spokenLanguages: 6, writtenLanguages: 4, auraControlAdjust: 2, initiativeAdjust: -9, controlResistAdjust: 20 },
		21: { spokenLanguages: 7, writtenLanguages: 5, auraControlAdjust: 3, initiativeAdjust: -10, controlResistAdjust: 25 },
		22: { spokenLanguages: 8, writtenLanguages: 6, auraControlAdjust: 3, initiativeAdjust: -11, controlResistAdjust: 30 },
		23: { spokenLanguages: 9, writtenLanguages: 7, auraControlAdjust: 4, initiativeAdjust: -12, controlResistAdjust: 35 },
		24: { spokenLanguages: 10, writtenLanguages: 8, auraControlAdjust: 4, initiativeAdjust: -13, controlResistAdjust: 40 },
		25: { spokenLanguages: 10, writtenLanguages: 9, auraControlAdjust: 5, initiativeAdjust: -14, controlResistAdjust: 45 },
		26: { spokenLanguages: 10, writtenLanguages: 10, auraControlAdjust: 5, initiativeAdjust: -15, controlResistAdjust: 50 },
		27: { spokenLanguages: 10, writtenLanguages: 10, auraControlAdjust: 6, initiativeAdjust: -16, controlResistAdjust: 55 },
		28: { spokenLanguages: 10, writtenLanguages: 10, auraControlAdjust: 8, initiativeAdjust: -17, controlResistAdjust: 60 },
		29: { spokenLanguages: 10, writtenLanguages: 10, auraControlAdjust: 10, initiativeAdjust: -18, controlResistAdjust: 65 },
		30: { spokenLanguages: 10, writtenLanguages: 10, auraControlAdjust: 15, initiativeAdjust: -21, controlResistAdjust: 70 },
	},

	// WIS -- columns: pietyControl, illusionResist, controlResistAdjust
	wis: {
		0: { pietyControl: -5, illusionResist: 0, controlResistAdjust: -40 },
		1: { pietyControl: -4, illusionResist: 0, controlResistAdjust: -35 },
		2: { pietyControl: -4, illusionResist: 0, controlResistAdjust: -30 },
		3: { pietyControl: -3, illusionResist: 0, controlResistAdjust: -25 },
		4: { pietyControl: -3, illusionResist: 0, controlResistAdjust: -20 },
		5: { pietyControl: -2, illusionResist: 1, controlResistAdjust: -15 },
		6: { pietyControl: -2, illusionResist: 2, controlResistAdjust: -10 },
		7: { pietyControl: -1, illusionResist: 5, controlResistAdjust: -5 },
		8: { pietyControl: -1, illusionResist: 10, controlResistAdjust: -5 },
		9: { pietyControl: 0, illusionResist: 15, controlResistAdjust: 0 },
		10: { pietyControl: 0, illusionResist: 20, controlResistAdjust: 0 },
		11: { pietyControl: 0, illusionResist: 25, controlResistAdjust: 0 },
		12: { pietyControl: 0, illusionResist: 30, controlResistAdjust: 0 },
		13: { pietyControl: 0, illusionResist: 35, controlResistAdjust: 0 },
		14: { pietyControl: 0, illusionResist: 40, controlResistAdjust: 0 },
		15: { pietyControl: 0, illusionResist: 45, controlResistAdjust: 0 },
		16: { pietyControl: 0, illusionResist: 50, controlResistAdjust: 0 },
		17: { pietyControl: 1, illusionResist: 55, controlResistAdjust: 5 },
		18: { pietyControl: 1, illusionResist: 60, controlResistAdjust: 5 },
		19: { pietyControl: 2, illusionResist: 65, controlResistAdjust: 10 },
		20: { pietyControl: 2, illusionResist: 70, controlResistAdjust: 15 },
		21: { pietyControl: 3, illusionResist: 75, controlResistAdjust: 20 },
		22: { pietyControl: 3, illusionResist: 80, controlResistAdjust: 25 },
		23: { pietyControl: 4, illusionResist: 85, controlResistAdjust: 30 },
		24: { pietyControl: 4, illusionResist: 90, controlResistAdjust: 35 },
		25: { pietyControl: 5, illusionResist: 95, controlResistAdjust: 40 },
		26: { pietyControl: 5, illusionResist: 100, controlResistAdjust: 45 },
		27: { pietyControl: 6, illusionResist: 100, controlResistAdjust: 50 },
		28: { pietyControl: 7, illusionResist: 100, controlResistAdjust: 55 },
		29: { pietyControl: 9, illusionResist: 100, controlResistAdjust: 60 },
		30: { pietyControl: 10, illusionResist: 200, controlResistAdjust: 65 },
	},

	// KNW -- columns: classSkills, raceSkills, socialSkills, memorizationPoints
	knw: {
		0: { classSkills: 0, raceSkills: 0, socialSkills: 0, memorizationPoints: 0 },
		1: { classSkills: 0, raceSkills: 0, socialSkills: 0, memorizationPoints: 0 },
		2: { classSkills: 1, raceSkills: 0, socialSkills: 0, memorizationPoints: 0 },
		3: { classSkills: 2, raceSkills: 0, socialSkills: 0, memorizationPoints: 0 },
		4: { classSkills: 3, raceSkills: 0, socialSkills: 0, memorizationPoints: 0 },
		5: { classSkills: 4, raceSkills: 1, socialSkills: 0, memorizationPoints: 0 },
		6: { classSkills: 8, raceSkills: 1, socialSkills: 0, memorizationPoints: 1 },
		7: { classSkills: 12, raceSkills: 1, socialSkills: 1, memorizationPoints: 1 },
		8: { classSkills: 16, raceSkills: 1, socialSkills: 1, memorizationPoints: 1 },
		9: { classSkills: 20, raceSkills: 1, socialSkills: 1, memorizationPoints: 2 },
		10: { classSkills: 24, raceSkills: 2, socialSkills: 1, memorizationPoints: 3 },
		11: { classSkills: 28, raceSkills: 3, socialSkills: 2, memorizationPoints: 4 },
		12: { classSkills: 32, raceSkills: 4, socialSkills: 3, memorizationPoints: 5 },
		13: { classSkills: 36, raceSkills: 5, socialSkills: 4, memorizationPoints: 6 },
		14: { classSkills: 40, raceSkills: 6, socialSkills: 5, memorizationPoints: 7 },
		15: { classSkills: 44, raceSkills: 7, socialSkills: 6, memorizationPoints: 8 },
		16: { classSkills: 48, raceSkills: 8, socialSkills: 7, memorizationPoints: 9 },
		17: { classSkills: 52, raceSkills: 9, socialSkills: 8, memorizationPoints: 10 },
		18: { classSkills: 56, raceSkills: 10, socialSkills: 9, memorizationPoints: 11 },
		19: { classSkills: 60, raceSkills: 12, socialSkills: 10, memorizationPoints: 12 },
		20: { classSkills: 64, raceSkills: 14, socialSkills: 12, memorizationPoints: 14 },
		21: { classSkills: 68, raceSkills: 16, socialSkills: 14, memorizationPoints: 16 },
		22: { classSkills: 72, raceSkills: 18, socialSkills: 16, memorizationPoints: 18 },
		23: { classSkills: 76, raceSkills: 20, socialSkills: 18, memorizationPoints: 20 },
		24: { classSkills: 80, raceSkills: 24, socialSkills: 20, memorizationPoints: 24 },
		25: { classSkills: 85, raceSkills: 28, socialSkills: 24, memorizationPoints: 30 },
		26: { classSkills: 90, raceSkills: 32, socialSkills: 28, memorizationPoints: 35 },
		27: { classSkills: 95, raceSkills: 36, socialSkills: 32, memorizationPoints: 40 },
		28: { classSkills: 100, raceSkills: 40, socialSkills: 36, memorizationPoints: 45 },
		29: { classSkills: 150, raceSkills: 44, socialSkills: 40, memorizationPoints: 50 },
		30: { classSkills: 150, raceSkills: 44, socialSkills: 40, memorizationPoints: 50 },
	},

	// APP -- columns: morale, controlAdjust, special, specialChance
	app: {
		0: { morale: -40, controlAdjust: 45, special: "Fear", specialChance: "80%" },
		1: { morale: -35, controlAdjust: 40, special: "Fear", specialChance: "60%" },
		2: { morale: -30, controlAdjust: 35, special: "Fear", specialChance: "40%" },
		3: { morale: -25, controlAdjust: 30, special: "Fear", specialChance: "20%" },
		4: { morale: -20, controlAdjust: 25, special: "Fear", specialChance: "10%" },
		5: { morale: -15, controlAdjust: 20, special: "", specialChance: "" },
		6: { morale: -15, controlAdjust: 15, special: "", specialChance: "" },
		7: { morale: -10, controlAdjust: 15, special: "", specialChance: "" },
		8: { morale: -10, controlAdjust: 10, special: "", specialChance: "" },
		9: { morale: -5, controlAdjust: 10, special: "", specialChance: "" },
		10: { morale: -5, controlAdjust: 5, special: "", specialChance: "" },
		11: { morale: -2, controlAdjust: 0, special: "", specialChance: "" },
		12: { morale: 0, controlAdjust: 0, special: "", specialChance: "" },
		13: { morale: 0, controlAdjust: 0, special: "", specialChance: "" },
		14: { morale: 2, controlAdjust: 0, special: "", specialChance: "" },
		15: { morale: 5, controlAdjust: -5, special: "", specialChance: "" },
		16: { morale: 5, controlAdjust: -10, special: "", specialChance: "" },
		17: { morale: 10, controlAdjust: -10, special: "", specialChance: "" },
		18: { morale: 10, controlAdjust: -15, special: "", specialChance: "" },
		19: { morale: 15, controlAdjust: -15, special: "", specialChance: "" },
		20: { morale: 15, controlAdjust: -20, special: "", specialChance: "" },
		21: { morale: 20, controlAdjust: -25, special: "Awe", specialChance: "5%" },
		22: { morale: 25, controlAdjust: -30, special: "Awe", specialChance: "10%" },
		23: { morale: 30, controlAdjust: -35, special: "Awe", specialChance: "15%" },
		24: { morale: 35, controlAdjust: -40, special: "Awe", specialChance: "20%" },
		25: { morale: 40, controlAdjust: -45, special: "Awe", specialChance: "25%" },
		26: { morale: 45, controlAdjust: -50, special: "Awe", specialChance: "30%" },
		27: { morale: 50, controlAdjust: -55, special: "Awe", specialChance: "35%" },
		28: { morale: 55, controlAdjust: -60, special: "Awe", specialChance: "40%" },
		29: { morale: 60, controlAdjust: -65, special: "Awe", specialChance: "45%" },
		30: { morale: 65, controlAdjust: -70, special: "Awe", specialChance: "50%" },
	},

	// CHM -- columns: morale, controlAdjust
	chm: {
		0: { morale: -40, controlAdjust: 45 },
		1: { morale: -35, controlAdjust: 40 },
		2: { morale: -30, controlAdjust: 35 },
		3: { morale: -25, controlAdjust: 30 },
		4: { morale: -20, controlAdjust: 25 },
		5: { morale: -15, controlAdjust: 20 },
		6: { morale: -15, controlAdjust: 15 },
		7: { morale: -10, controlAdjust: 15 },
		8: { morale: -10, controlAdjust: 10 },
		9: { morale: -5, controlAdjust: 10 },
		10: { morale: -5, controlAdjust: 5 },
		11: { morale: -2, controlAdjust: 0 },
		12: { morale: 0, controlAdjust: 0 },
		13: { morale: 0, controlAdjust: 0 },
		14: { morale: 2, controlAdjust: 0 },
		15: { morale: 5, controlAdjust: -5 },
		16: { morale: 5, controlAdjust: -10 },
		17: { morale: 10, controlAdjust: -10 },
		18: { morale: 10, controlAdjust: -15 },
		19: { morale: 15, controlAdjust: -15 },
		20: { morale: 15, controlAdjust: -20 },
		21: { morale: 20, controlAdjust: -25 },
		22: { morale: 25, controlAdjust: -30 },
		23: { morale: 30, controlAdjust: -35 },
		24: { morale: 35, controlAdjust: -40 },
		25: { morale: 40, controlAdjust: -45 },
		26: { morale: 45, controlAdjust: -50 },
		27: { morale: 50, controlAdjust: -55 },
		28: { morale: 55, controlAdjust: -60 },
		29: { morale: 60, controlAdjust: -65 },
		30: { morale: 65, controlAdjust: -70 },
	},

	// SOC -- columns: morale, rank
	soc: {
		0: { morale: -40, rank: "Damned Soul" },
		1: { morale: -35, rank: "Condemned Soul" },
		2: { morale: -30, rank: "Tortured Soul" },
		3: { morale: -25, rank: "Tormented Soul" },
		4: { morale: -20, rank: "Lost Soul" },
		5: { morale: -15, rank: "Slave/Escaped Slave" },
		6: { morale: -15, rank: "Freed Slave/Indentured" },
		7: { morale: -10, rank: "Peasant/Serf or Tribesperson" },
		8: { morale: -10, rank: "Peasant/Serf or Tribesperson" },
		9: { morale: -5, rank: "Commoner/Skilled Laborer" },
		10: { morale: -5, rank: "Commoner/Skilled Laborer" },
		11: { morale: -2, rank: "Tradesperson/Craftsperson" },
		12: { morale: 0, rank: "Tradesperson/Craftsperson" },
		13: { morale: 0, rank: "Master Tradesperson/Craftsperson" },
		14: { morale: 2, rank: "Master Tradesperson/Craftsperson" },
		15: { morale: 5, rank: "Noble:Knight Bannerete(family of)" },
		16: { morale: 5, rank: "Noble:Baron (family of)" },
		17: { morale: 10, rank: "Noble:Count (family of)" },
		18: { morale: 10, rank: "Noble:Earl (family of)" },
		19: { morale: 15, rank: "Noble:Duke (family of)" },
		20: { morale: 15, rank: "Noble:King (family of)" },
		21: { morale: 20, rank: "Chosen Soul" },
		22: { morale: 25, rank: "Honored Soul" },
		23: { morale: 30, rank: "Privileged Soul" },
		24: { morale: 35, rank: "Lesser Supernatural" },
		25: { morale: 40, rank: "Minor Supernatural" },
		26: { morale: 45, rank: "Major Supernatural" },
		27: { morale: 50, rank: "Arch Supernatural" },
		28: { morale: 55, rank: "Semi-Deity" },
		29: { morale: 60, rank: "Deity" },
		30: { morale: 65, rank: "Supreme Deity" },
	},

	// AUR -- columns: magicResist, regenBonusLabel, regenBonus
	aur: {
		0: { magicResist: 0, regenBonusLabel: "", regenBonus: "" },
		1: { magicResist: 0, regenBonusLabel: "", regenBonus: "" },
		2: { magicResist: 0, regenBonusLabel: "", regenBonus: "" },
		3: { magicResist: 0, regenBonusLabel: "", regenBonus: "" },
		4: { magicResist: 0, regenBonusLabel: "", regenBonus: "" },
		5: { magicResist: 1, regenBonusLabel: "", regenBonus: "" },
		6: { magicResist: 2, regenBonusLabel: "", regenBonus: "" },
		7: { magicResist: 4, regenBonusLabel: "", regenBonus: "" },
		8: { magicResist: 6, regenBonusLabel: "", regenBonus: "" },
		9: { magicResist: 8, regenBonusLabel: "", regenBonus: "" },
		10: { magicResist: 10, regenBonusLabel: "", regenBonus: "" },
		11: { magicResist: 15, regenBonusLabel: "", regenBonus: "" },
		12: { magicResist: 20, regenBonusLabel: "", regenBonus: "" },
		13: { magicResist: 25, regenBonusLabel: "", regenBonus: "" },
		14: { magicResist: 30, regenBonusLabel: "", regenBonus: "" },
		15: { magicResist: 35, regenBonusLabel: "", regenBonus: "" },
		16: { magicResist: 40, regenBonusLabel: "", regenBonus: "" },
		17: { magicResist: 45, regenBonusLabel: "", regenBonus: "" },
		18: { magicResist: 50, regenBonusLabel: "", regenBonus: "" },
		19: { magicResist: 55, regenBonusLabel: "", regenBonus: "" },
		20: { magicResist: 60, regenBonusLabel: "", regenBonus: "" },
		21: { magicResist: 60, regenBonusLabel: "", regenBonus: "" },
		22: { magicResist: 65, regenBonusLabel: "", regenBonus: "" },
		23: { magicResist: 70, regenBonusLabel: "", regenBonus: "" },
		24: { magicResist: 75, regenBonusLabel: "", regenBonus: "" },
		25: { magicResist: 80, regenBonusLabel: "Aura Regen", regenBonus: "+1 per Second" },
		26: { magicResist: 85, regenBonusLabel: "Aura Regen", regenBonus: "+2 per Second" },
		27: { magicResist: 90, regenBonusLabel: "Aura Regen", regenBonus: "+3 per Second" },
		28: { magicResist: 95, regenBonusLabel: "Aura Regen", regenBonus: "+4 per Second" },
		29: { magicResist: 99, regenBonusLabel: "Aura Regen", regenBonus: "+5 per Second" },
		30: { magicResist: 200, regenBonusLabel: "Aura Regen", regenBonus: "+10 per Second" },
	},

	// PTY -- columns: commune, specialLabel, specialNum
	pty: {
		0: { commune: 0, specialLabel: "Disfavor", specialNum: "10" },
		1: { commune: 0, specialLabel: "Disfavor", specialNum: "8" },
		2: { commune: 0, specialLabel: "Disfavor", specialNum: "6" },
		3: { commune: 0, specialLabel: "Disfavor", specialNum: "4" },
		4: { commune: 0, specialLabel: "Disfavor", specialNum: "2" },
		5: { commune: 0, specialLabel: "", specialNum: "" },
		6: { commune: 0, specialLabel: "", specialNum: "" },
		7: { commune: 0, specialLabel: "", specialNum: "" },
		8: { commune: 0, specialLabel: "", specialNum: "" },
		9: { commune: 0, specialLabel: "", specialNum: "" },
		10: { commune: 0, specialLabel: "", specialNum: "" },
		11: { commune: 0, specialLabel: "", specialNum: "" },
		12: { commune: 0, specialLabel: "", specialNum: "" },
		13: { commune: 0, specialLabel: "", specialNum: "" },
		14: { commune: 1, specialLabel: "", specialNum: "" },
		15: { commune: 1, specialLabel: "", specialNum: "" },
		16: { commune: 2, specialLabel: "", specialNum: "" },
		17: { commune: 4, specialLabel: "", specialNum: "" },
		18: { commune: 6, specialLabel: "", specialNum: "" },
		19: { commune: 8, specialLabel: "", specialNum: "" },
		20: { commune: 10, specialLabel: "", specialNum: "" },
		21: { commune: 12, specialLabel: "Favor", specialNum: "1" },
		22: { commune: 14, specialLabel: "Favor", specialNum: "2" },
		23: { commune: 16, specialLabel: "Favor", specialNum: "3" },
		24: { commune: 18, specialLabel: "Favor", specialNum: "4" },
		25: { commune: 20, specialLabel: "Favor", specialNum: "5" },
		26: { commune: 22, specialLabel: "Favor", specialNum: "6" },
		27: { commune: 24, specialLabel: "Favor", specialNum: "7" },
		28: { commune: 26, specialLabel: "Favor", specialNum: "8" },
		29: { commune: 28, specialLabel: "Favor", specialNum: "9" },
		30: { commune: 30, specialLabel: "Favor", specialNum: "10" },
	},

	// WIL -- columns: controlResist, endure, specialLabel, specialNum
	wil: {
		0: { controlResist: 0, endure: 0, specialLabel: "", specialNum: "" },
		1: { controlResist: 0, endure: 0, specialLabel: "", specialNum: "" },
		2: { controlResist: 0, endure: 0, specialLabel: "", specialNum: "" },
		3: { controlResist: 0, endure: 0, specialLabel: "", specialNum: "" },
		4: { controlResist: 0, endure: 0, specialLabel: "", specialNum: "" },
		5: { controlResist: 1, endure: 0, specialLabel: "", specialNum: "" },
		6: { controlResist: 2, endure: 0, specialLabel: "", specialNum: "" },
		7: { controlResist: 4, endure: 0, specialLabel: "", specialNum: "" },
		8: { controlResist: 6, endure: 0, specialLabel: "", specialNum: "" },
		9: { controlResist: 8, endure: 0, specialLabel: "", specialNum: "" },
		10: { controlResist: 10, endure: 0, specialLabel: "", specialNum: "" },
		11: { controlResist: 15, endure: 0, specialLabel: "", specialNum: "" },
		12: { controlResist: 20, endure: 0, specialLabel: "", specialNum: "" },
		13: { controlResist: 25, endure: 0, specialLabel: "", specialNum: "" },
		14: { controlResist: 30, endure: 0, specialLabel: "", specialNum: "" },
		15: { controlResist: 35, endure: 1, specialLabel: "", specialNum: "" },
		16: { controlResist: 40, endure: 2, specialLabel: "", specialNum: "" },
		17: { controlResist: 45, endure: 4, specialLabel: "", specialNum: "" },
		18: { controlResist: 50, endure: 6, specialLabel: "", specialNum: "" },
		19: { controlResist: 55, endure: 8, specialLabel: "", specialNum: "" },
		20: { controlResist: 60, endure: 10, specialLabel: "", specialNum: "" },
		21: { controlResist: 65, endure: 12, specialLabel: "", specialNum: "" },
		22: { controlResist: 70, endure: 14, specialLabel: "", specialNum: "" },
		23: { controlResist: 75, endure: 16, specialLabel: "", specialNum: "" },
		24: { controlResist: 80, endure: 18, specialLabel: "", specialNum: "" },
		25: { controlResist: 85, endure: 20, specialLabel: "", specialNum: "" },
		26: { controlResist: 90, endure: 22, specialLabel: "Will Reservoir", specialNum: "25" },
		27: { controlResist: 99, endure: 24, specialLabel: "Will Reservoir", specialNum: "50" },
		28: { controlResist: 100, endure: 26, specialLabel: "Will Reservoir", specialNum: "75" },
		29: { controlResist: 100, endure: 28, specialLabel: "Will Reservoir", specialNum: "100" },
		30: { controlResist: 100, endure: 30, specialLabel: "Will Reservoir", specialNum: "ALL" },
	},
};

// @END (CODE)
